// Flavor text only — every actual answer comes from the real
// recommendation engine / TMDB data. Nothing here is generated by an LLM;
// keeping the assistant's "intelligence" scoped to what the deterministic
// recommendation system can already back up.

export const GREETING_LINES = [
  "Scanning your cinematic preferences…",
  "Systems online. Ready when you are.",
  "500,000+ movie relationships, one good pick.",
];

export const THINKING_LINES: Record<"recommend" | "trending" | "surprise" | "search", string[]> = {
  recommend: ["Scanning your taste profile…", "Cross-referencing genres and cast…", "Calculating match confidence…"],
  trending: ["Pulling this week's signal…", "Checking what's spiking right now…"],
  surprise: ["Digging for a hidden gem…", "Searching the deep catalog…"],
  search: ["Searching the archive…"],
};

export function randomLine(lines: string[]): string {
  return lines[Math.floor(Math.random() * lines.length)];
}
