import { GENRE } from "@/lib/tmdb-genres";
import type { JourneyDefinition } from "@/types/journey";

// DISCOVERY journeys — generated from rating, vote, popularity, and
// release-date metadata, plus director/actor filmographies.
//
// Deliberately NOT included, because TMDB exposes no reliable metadata for
// them and inventing membership would be fabricating data:
//  - "Award Winners" (no awards data in TMDB's API)
//  - "Breakout Performances" (no notion of a breakout role)

const NO_TV = [GENRE.tvMovie];

export const DISCOVERY_JOURNEYS: JourneyDefinition[] = [
  {
    id: "discovery-hidden-gems",
    type: "discovery",
    name: "Hidden Gems",
    shortName: "Hidden Gems",
    description: "Excellent films with a small audience — high ratings, low vote counts, low popularity.",
    aliases: ["hidden gem", "hidden gems", "lesser known"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 3 },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], minVotes: 150, maxVotes: 1500, minRating: 7.3, maxPopularity: 40, minRuntime: 60 },
    ranking: { quality: 0.8, consensus: 0.2 },
    selection: { maxMovies: 15, perDecadeCap: 4 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-underrated",
    type: "discovery",
    name: "Underrated",
    shortName: "Underrated",
    description: "Well-rated older films that never found the audience they deserved.",
    aliases: ["underrated", "overlooked"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 3 },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], minVotes: 80, maxVotes: 800, minRating: 7, releasedBeforeYear: 2012, minRuntime: 60 },
    ranking: { quality: 0.75, consensus: 0.25 },
    selection: { maxMovies: 15, perDecadeCap: 4 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-critically-acclaimed",
    type: "discovery",
    name: "Critically Acclaimed",
    shortName: "Acclaimed",
    description: "The highest-rated films with the broadest consensus behind them.",
    aliases: ["acclaimed", "best movies", "masterpieces", "all time best"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 2 },
    rules: { excludeGenres: NO_TV, minVotes: 5000, minRating: 8 },
    ranking: { quality: 0.7, consensus: 0.3 },
    selection: { maxMovies: 20, perDecadeCap: 5 },
    minimumMovies: 10,
    freshness: "daily",
  },
  {
    id: "discovery-cult-favorites",
    type: "discovery",
    name: "Cult Favorites",
    shortName: "Cult Favorites",
    description: "Films TMDB tags as cult classics — the ones that found their people.",
    aliases: ["cult", "cult classic", "cult film"],
    source: { kind: "keyword", keywords: ["cult film", "cult classic"], sortBy: "vote_count.desc", pages: 3 },
    rules: { excludeGenres: NO_TV, minVotes: 300, minRating: 6.8 },
    ranking: { quality: 0.5, consensus: 0.5 },
    selection: { maxMovies: 15, perDecadeCap: 4 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-modern-classics",
    type: "discovery",
    name: "Modern Classics",
    shortName: "Modern Classics",
    description: "Films from 2000 onward that have already earned classic status.",
    aliases: ["modern classics", "instant classics"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 2 },
    rules: { excludeGenres: NO_TV, releasedAfterYear: 2000, minVotes: 8000, minRating: 7.8 },
    ranking: { quality: 0.6, consensus: 0.4 },
    selection: { maxMovies: 18 },
    minimumMovies: 10,
    freshness: "daily",
  },
  {
    id: "discovery-international-cinema",
    type: "discovery",
    name: "International Cinema",
    shortName: "International",
    description: "The best-regarded films not originally in English — at most three per language.",
    aliases: ["international", "world cinema", "foreign", "foreign language"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 5 },
    rules: { excludeGenres: NO_TV, excludeLanguages: ["en"], minVotes: 1500, minRating: 7.8 },
    ranking: { quality: 0.7, consensus: 0.3 },
    selection: { maxMovies: 18, perLanguageCap: 3 },
    minimumMovies: 10,
    freshness: "daily",
  },
  {
    id: "discovery-highly-rated-debuts",
    type: "discovery",
    name: "Highly Rated Debuts",
    shortName: "Debuts",
    description: "Directorial debuts TMDB tags as such, filtered to the best-rated.",
    aliases: ["debut", "first film", "directorial debut"],
    source: { kind: "keyword", keywords: ["directorial debut", "debut film"], sortBy: "vote_count.desc", pages: 3 },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], minVotes: 300, minRating: 7 },
    ranking: { quality: 0.7, consensus: 0.3 },
    selection: { maxMovies: 15, perDecadeCap: 4 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-recent-discoveries",
    type: "discovery",
    name: "Recent Discoveries",
    shortName: "Recent Discoveries",
    description: "Well-reviewed films from the last two years — refreshed daily.",
    aliases: ["new and good", "recent", "latest"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 3 },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], releasedWithinDays: 730, minVotes: 150, minRating: 7, minRuntime: 60 },
    ranking: { quality: 0.6, consensus: 0.25, recency: 0.15 },
    selection: { maxMovies: 15 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-recent-critically-acclaimed",
    type: "discovery",
    name: "Recent Critically Acclaimed",
    shortName: "Recent Acclaimed",
    description: "The best-rated films of the last three years with real consensus behind them.",
    aliases: ["recent acclaimed", "best of recent years"],
    source: { kind: "discover", sortBy: "vote_average.desc", pages: 2 },
    rules: { excludeGenres: NO_TV, releasedWithinDays: 1095, minVotes: 800, minRating: 7.5 },
    ranking: { quality: 0.65, consensus: 0.35 },
    selection: { maxMovies: 15 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-recent-releases",
    type: "discovery",
    name: "Recent Releases",
    shortName: "Recent Releases",
    description: "What's come out in the last four months, ranked by rating and attention.",
    aliases: ["new releases", "just released", "new movies"],
    source: { kind: "discover", sortBy: "popularity.desc", pages: 3 },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], releasedWithinDays: 120, minVotes: 40, minRuntime: 60 },
    ranking: { quality: 0.4, popularity: 0.4, recency: 0.2, priorVotes: 100 },
    selection: { maxMovies: 15 },
    minimumMovies: 8,
    freshness: "daily",
  },
  {
    id: "discovery-popular-this-week",
    type: "discovery",
    name: "Popular This Week",
    shortName: "This Week",
    description: "Straight from TMDB's weekly trending chart — membership changes as the chart does.",
    aliases: ["trending", "popular now", "this week"],
    source: { kind: "trending", window: "week", pages: 2 },
    rules: { excludeGenres: NO_TV, minVotes: 20 },
    ranking: { popularity: 0.7, quality: 0.3, priorVotes: 100 },
    selection: { maxMovies: 15 },
    minimumMovies: 8,
    freshness: "hourly",
  },
  {
    id: "discovery-trending-hidden-gems",
    type: "discovery",
    name: "Trending Hidden Gems",
    shortName: "Trending Gems",
    description: "Well-rated films on this week's trending chart that still have a small audience.",
    aliases: ["trending gems"],
    source: { kind: "trending", window: "week", pages: 5 },
    rules: { excludeGenres: NO_TV, minVotes: 30, maxVotes: 2000, minRating: 7 },
    ranking: { quality: 0.6, popularity: 0.4, priorVotes: 100 },
    selection: { maxMovies: 12 },
    minimumMovies: 6,
    freshness: "hourly",
  },
  {
    id: "discovery-new-indian-cinema",
    type: "discovery",
    name: "New Indian Cinema",
    shortName: "New Indian",
    description: "Indian-produced films from the past year across every language — refreshed daily.",
    aliases: ["new indian", "indian new releases", "latest indian"],
    source: { kind: "discover", sortBy: "popularity.desc", pages: 3 },
    rules: { originCountry: "IN", excludeGenres: [...NO_TV, GENRE.documentary], releasedWithinDays: 365, minVotes: 10 },
    ranking: { quality: 0.5, popularity: 0.3, recency: 0.2, priorVotes: 30 },
    selection: { maxMovies: 15, perLanguageCap: 5 },
    minimumMovies: 8,
    freshness: "daily",
  },

  // --- Director spotlights: a director's filmography (as director), best-regarded first, walked in release order.
  ...[
    { slug: "christopher-nolan", name: "Christopher Nolan" },
    { slug: "denis-villeneuve", name: "Denis Villeneuve" },
    { slug: "hayao-miyazaki", name: "Hayao Miyazaki" },
    { slug: "akira-kurosawa", name: "Akira Kurosawa" },
    { slug: "martin-scorsese", name: "Martin Scorsese" },
    { slug: "steven-spielberg", name: "Steven Spielberg" },
    { slug: "bong-joon-ho", name: "Bong Joon Ho" },
    { slug: "satyajit-ray", name: "Satyajit Ray", minVotes: 15 },
    { slug: "mani-ratnam", name: "Mani Ratnam", minVotes: 15 },
    { slug: "ss-rajamouli", name: "S. S. Rajamouli", minVotes: 15 },
  ].map(({ slug, name, minVotes }): JourneyDefinition => ({
    id: `director-${slug}`,
    type: "discovery",
    name: `Director Spotlight: ${name}`,
    shortName: name,
    description: `${name}'s films as director, from TMDB's credits — walked in release order.`,
    aliases: [name.toLowerCase(), `${name.toLowerCase()} films`, "director spotlight"],
    source: { kind: "person", name, role: "director" },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], minVotes: minVotes ?? 100 },
    ranking: { quality: 0.5, consensus: 0.5, priorVotes: minVotes ? 30 : 300 },
    selection: { maxMovies: 20 },
    minimumMovies: 5,
    freshness: "weekly",
  })),

  // --- Actor spotlights: films where the actor is top-billed (first three credits).
  ...[
    { slug: "tom-hanks", name: "Tom Hanks" },
    { slug: "denzel-washington", name: "Denzel Washington" },
    { slug: "meryl-streep", name: "Meryl Streep" },
    { slug: "shah-rukh-khan", name: "Shah Rukh Khan", minVotes: 30 },
    { slug: "amitabh-bachchan", name: "Amitabh Bachchan", minVotes: 20 },
    { slug: "mohanlal", name: "Mohanlal", minVotes: 15 },
    { slug: "rajinikanth", name: "Rajinikanth", minVotes: 15 },
    { slug: "kamal-haasan", name: "Kamal Haasan", minVotes: 15 },
  ].map(({ slug, name, minVotes }): JourneyDefinition => ({
    id: `actor-${slug}`,
    type: "discovery",
    name: `Actor Spotlight: ${name}`,
    shortName: name,
    description: `Films where ${name} is top-billed, from TMDB's credits — walked in release order.`,
    aliases: [name.toLowerCase(), `${name.toLowerCase()} movies`, "actor spotlight"],
    source: { kind: "person", name, role: "lead" },
    rules: { excludeGenres: [...NO_TV, GENRE.documentary], minVotes: minVotes ?? 300 },
    ranking: { quality: 0.5, consensus: 0.5, priorVotes: minVotes ? 30 : 300 },
    selection: { maxMovies: 20, perDecadeCap: 5 },
    minimumMovies: 6,
    freshness: "weekly",
  })),
];
