import { GENRE } from "@/lib/tmdb-genres";
import type { CuratedJourneyMovie, FranchiseKind, JourneyDefinition, JourneyOrderType } from "@/types/journey";
import { TMDB_COLLECTION_IDS } from "./tmdb-collections";

// FRANCHISE journeys — every kind: shared cinematic universes, long-running
// series, trilogies, superhero, sci-fi/fantasy, animated, family, comedy,
// horror, crime, drama/romance, Indian (Telugu, Tamil, Hindi, Malayalam,
// Kannada), and world cinema.
//
// Two membership sources, both strong signals:
//  - `curated`: hand-verified title + year lists, used for shared universes
//    TMDB has no single collection for (and for the original five, whose
//    chronological/"essential" orders are documented). Alternate orders
//    only appear where they're officially documented — never invented.
//  - `collection`: TMDB's own collection (series) membership. Every name
//    below was verified against TMDB and its id recorded in
//    ./tmdb-collections.ts. Release order only.
// Unreleased entries, TV movies, and near-unrated titles never count; a
// franchise with fewer than two qualifying films isn't shown.

interface CuratedSpec {
  id: string;
  name: string;
  shortName: string;
  kind: FranchiseKind;
  description: string;
  aliases: string[];
  orders: JourneyOrderType[];
  movies: CuratedJourneyMovie[];
  minimumMovies?: number;
}

function curated(spec: CuratedSpec): JourneyDefinition {
  return {
    id: spec.id,
    type: "franchise",
    franchiseKind: spec.kind,
    name: spec.name,
    shortName: spec.shortName,
    description: spec.description,
    aliases: spec.aliases,
    source: { kind: "curated", movies: spec.movies, orders: spec.orders },
    minimumMovies: spec.minimumMovies ?? Math.min(3, spec.movies.length),
    freshness: "weekly",
  };
}

/** Release-order list from `[title, year]` pairs, optionally with a documented chronological position. */
function inOrder(entries: [title: string, year: string, chronological?: number][]): CuratedJourneyMovie[] {
  return entries.map(([title, releaseYear, chronologicalOrder], index) => ({
    title,
    releaseYear,
    releaseOrder: index + 1,
    ...(chronologicalOrder !== undefined ? { chronologicalOrder } : {}),
  }));
}

function collection(
  id: string,
  name: string,
  kind: FranchiseKind,
  collections: string[],
  description: string,
  aliases: string[] = [],
  shortName: string = name
): JourneyDefinition {
  return {
    id,
    type: "franchise",
    franchiseKind: kind,
    name,
    shortName,
    description,
    aliases: [name.toLowerCase(), ...aliases],
    source: {
      kind: "collection",
      collections: collections.map((collectionName) => {
        const collectionId = TMDB_COLLECTION_IDS[collectionName];
        if (!collectionId) throw new Error(`No verified TMDB collection id for "${collectionName}" (journey ${id})`);
        return { name: collectionName, id: collectionId };
      }),
    },
    // Released, genuinely-rated theatrical films only.
    rules: { minVotes: 20, excludeGenres: [GENRE.tvMovie] },
    selection: { maxMovies: 30 },
    minimumMovies: 2,
    freshness: "weekly",
  };
}

// --- Shared universes & the original curated sagas -----------------------------------

const CURATED: JourneyDefinition[] = [
  curated({
    id: "mcu-infinity-saga",
    name: "Marvel Cinematic Universe",
    shortName: "MCU",
    kind: "universe",
    description: "The Infinity Saga — 23 films across three phases, from a billionaire in a cave to the fight for the entire universe.",
    aliases: ["marvel", "mcu", "avengers", "infinity saga"],
    orders: ["release", "chronological", "essential"],
    minimumMovies: 10,
    movies: [
      { title: "Iron Man", releaseYear: "2008", releaseOrder: 1, chronologicalOrder: 3, isEssential: true },
      { title: "The Incredible Hulk", releaseYear: "2008", releaseOrder: 2, chronologicalOrder: 5 },
      { title: "Iron Man 2", releaseYear: "2010", releaseOrder: 3, chronologicalOrder: 4 },
      { title: "Thor", releaseYear: "2011", releaseOrder: 4, chronologicalOrder: 6 },
      { title: "Captain America: The First Avenger", releaseYear: "2011", releaseOrder: 5, chronologicalOrder: 1, isEssential: true },
      { title: "The Avengers", releaseYear: "2012", releaseOrder: 6, chronologicalOrder: 7, isEssential: true },
      { title: "Iron Man 3", releaseYear: "2013", releaseOrder: 7, chronologicalOrder: 9 },
      { title: "Thor: The Dark World", releaseYear: "2013", releaseOrder: 8, chronologicalOrder: 8 },
      { title: "Captain America: The Winter Soldier", releaseYear: "2014", releaseOrder: 9, chronologicalOrder: 10, isEssential: true },
      { title: "Guardians of the Galaxy", releaseYear: "2014", releaseOrder: 10, chronologicalOrder: 11, isEssential: true },
      { title: "Avengers: Age of Ultron", releaseYear: "2015", releaseOrder: 11, chronologicalOrder: 13, isEssential: true },
      { title: "Ant-Man", releaseYear: "2015", releaseOrder: 12, chronologicalOrder: 14 },
      { title: "Captain America: Civil War", releaseYear: "2016", releaseOrder: 13, chronologicalOrder: 15, isEssential: true },
      { title: "Doctor Strange", releaseYear: "2016", releaseOrder: 14, chronologicalOrder: 18 },
      { title: "Guardians of the Galaxy Vol. 2", releaseYear: "2017", releaseOrder: 15, chronologicalOrder: 12 },
      { title: "Spider-Man: Homecoming", releaseYear: "2017", releaseOrder: 16, chronologicalOrder: 17 },
      { title: "Thor: Ragnarok", releaseYear: "2017", releaseOrder: 17, chronologicalOrder: 19, isEssential: true },
      { title: "Black Panther", releaseYear: "2018", releaseOrder: 18, chronologicalOrder: 16, isEssential: true },
      { title: "Avengers: Infinity War", releaseYear: "2018", releaseOrder: 19, chronologicalOrder: 20, isEssential: true },
      { title: "Ant-Man and the Wasp", releaseYear: "2018", releaseOrder: 20, chronologicalOrder: 21 },
      { title: "Captain Marvel", releaseYear: "2019", releaseOrder: 21, chronologicalOrder: 2, isEssential: true },
      { title: "Avengers: Endgame", releaseYear: "2019", releaseOrder: 22, chronologicalOrder: 22, isEssential: true },
      { title: "Spider-Man: Far From Home", releaseYear: "2019", releaseOrder: 23, chronologicalOrder: 23 },
    ],
  }),
  {
    id: "dc-extended-universe",
    type: "franchise",
    franchiseKind: "universe",
    name: "DC Extended Universe",
    shortName: "DCEU",
    description: "The shared DC film universe from Man of Steel onward — membership taken from TMDB's own DCEU tagging.",
    aliases: ["dc", "dceu", "justice league"],
    source: { kind: "keyword", keywords: ["dc extended universe (dceu)", "dc extended universe"], sortBy: "primary_release_date.desc", pages: 2 },
    rules: { minVotes: 200, excludeGenres: [GENRE.tvMovie] },
    selection: { maxMovies: 20 },
    minimumMovies: 6,
    freshness: "weekly",
  },
  curated({
    id: "wizarding-world",
    name: "Wizarding World",
    shortName: "Wizarding World",
    kind: "universe",
    description: "All eleven films — the eight Harry Potter films and the three Fantastic Beasts prequels, which are set decades earlier.",
    aliases: ["wizarding world", "fantastic beasts", "harry potter universe", "hogwarts"],
    orders: ["release", "chronological"],
    movies: inOrder([
      ["Harry Potter and the Philosopher's Stone", "2001", 4],
      ["Harry Potter and the Chamber of Secrets", "2002", 5],
      ["Harry Potter and the Prisoner of Azkaban", "2004", 6],
      ["Harry Potter and the Goblet of Fire", "2005", 7],
      ["Harry Potter and the Order of the Phoenix", "2007", 8],
      ["Harry Potter and the Half-Blood Prince", "2009", 9],
      ["Harry Potter and the Deathly Hallows: Part 1", "2010", 10],
      ["Harry Potter and the Deathly Hallows: Part 2", "2011", 11],
      ["Fantastic Beasts and Where to Find Them", "2016", 1],
      ["Fantastic Beasts: The Crimes of Grindelwald", "2018", 2],
      ["Fantastic Beasts: The Secrets of Dumbledore", "2022", 3],
    ]),
  }),
  curated({
    id: "middle-earth",
    name: "Middle-earth Saga",
    shortName: "Middle-earth",
    kind: "universe",
    description: "The Lord of the Rings and The Hobbit trilogies — made in one order, set in the other.",
    aliases: ["middle earth", "middle-earth", "tolkien", "the hobbit"],
    orders: ["release", "chronological"],
    movies: inOrder([
      ["The Lord of the Rings: The Fellowship of the Ring", "2001", 4],
      ["The Lord of the Rings: The Two Towers", "2002", 5],
      ["The Lord of the Rings: The Return of the King", "2003", 6],
      ["The Hobbit: An Unexpected Journey", "2012", 1],
      ["The Hobbit: The Desolation of Smaug", "2013", 2],
      ["The Hobbit: The Battle of the Five Armies", "2014", 3],
    ]),
  }),
  curated({
    id: "star-wars-skywalker-saga",
    name: "Star Wars: Skywalker Saga",
    shortName: "Star Wars",
    kind: "scifi-fantasy",
    description: "Nine films, three trilogies — the rise and fall of the Skywalker family, told across two very different orders.",
    aliases: ["star wars", "skywalker", "jedi"],
    orders: ["release", "chronological"],
    minimumMovies: 5,
    movies: [
      { title: "Star Wars: Episode IV - A New Hope", releaseYear: "1977", releaseOrder: 1, chronologicalOrder: 4 },
      { title: "Star Wars: Episode V - The Empire Strikes Back", releaseYear: "1980", releaseOrder: 2, chronologicalOrder: 5 },
      { title: "Star Wars: Episode VI - Return of the Jedi", releaseYear: "1983", releaseOrder: 3, chronologicalOrder: 6 },
      { title: "Star Wars: Episode I - The Phantom Menace", releaseYear: "1999", releaseOrder: 4, chronologicalOrder: 1 },
      { title: "Star Wars: Episode II - Attack of the Clones", releaseYear: "2002", releaseOrder: 5, chronologicalOrder: 2 },
      { title: "Star Wars: Episode III - Revenge of the Sith", releaseYear: "2005", releaseOrder: 6, chronologicalOrder: 3 },
      { title: "Star Wars: The Force Awakens", releaseYear: "2015", releaseOrder: 7, chronologicalOrder: 7 },
      { title: "Star Wars: The Last Jedi", releaseYear: "2017", releaseOrder: 8, chronologicalOrder: 8 },
      { title: "Star Wars: The Rise of Skywalker", releaseYear: "2019", releaseOrder: 9, chronologicalOrder: 9 },
    ],
  }),
  curated({
    id: "conjuring-universe",
    name: "The Conjuring Universe",
    shortName: "Conjuring Universe",
    kind: "universe",
    description: "The Conjuring films and their Annabelle, Nun, and La Llorona spin-offs — in release order or along the in-story timeline (1952–1986).",
    aliases: ["conjuring", "annabelle", "the nun", "warrens", "conjuring universe"],
    orders: ["release", "chronological"],
    movies: inOrder([
      ["The Conjuring", "2013", 5],
      ["Annabelle", "2014", 4],
      ["The Conjuring 2", "2016", 8],
      ["Annabelle: Creation", "2017", 2],
      ["The Nun", "2018", 1],
      ["The Curse of La Llorona", "2019", 7],
      ["Annabelle Comes Home", "2019", 6],
      ["The Conjuring: The Devil Made Me Do It", "2021", 9],
      ["The Nun II", "2023", 3],
      ["The Conjuring: Last Rites", "2025", 10],
    ]),
  }),
  curated({
    id: "monsterverse",
    name: "MonsterVerse",
    shortName: "MonsterVerse",
    kind: "universe",
    description: "Godzilla, Kong, and the Titans — Kong: Skull Island is set decades before the rest.",
    aliases: ["monsterverse", "godzilla", "kong", "titans"],
    orders: ["release", "chronological"],
    movies: inOrder([
      ["Godzilla", "2014", 2],
      ["Kong: Skull Island", "2017", 1],
      ["Godzilla: King of the Monsters", "2019", 3],
      ["Godzilla vs. Kong", "2021", 4],
      ["Godzilla x Kong: The New Empire", "2024", 5],
    ]),
  }),
  curated({
    id: "yrf-spy-universe",
    name: "YRF Spy Universe",
    shortName: "YRF Spy Universe",
    kind: "indian-universe",
    description: "Yash Raj Films' connected spy thrillers — Tiger, Kabir, and Pathaan's missions in release order.",
    aliases: ["spy universe", "yrf", "tiger", "pathaan", "war", "salman khan", "shah rukh khan", "hrithik roshan"],
    orders: ["release"],
    movies: inOrder([
      ["Ek Tha Tiger", "2012"],
      ["Tiger Zinda Hai", "2017"],
      ["War", "2019"],
      ["Pathaan", "2023"],
      ["Tiger 3", "2023"],
      ["War 2", "2025"],
    ]),
  }),
  curated({
    id: "rohit-shetty-cop-universe",
    name: "Rohit Shetty's Cop Universe",
    shortName: "Cop Universe",
    kind: "indian-universe",
    description: "Singham, Simmba, and Sooryavanshi — Rohit Shetty's crossover cop films in release order.",
    aliases: ["cop universe", "singham", "simmba", "sooryavanshi", "rohit shetty", "ajay devgn"],
    orders: ["release"],
    movies: inOrder([
      ["Singham", "2011"],
      ["Singham Returns", "2014"],
      ["Simmba", "2018"],
      ["Sooryavanshi", "2021"],
      ["Singham Again", "2024"],
    ]),
  }),
  curated({
    id: "lokesh-cinematic-universe",
    name: "Lokesh Cinematic Universe",
    shortName: "LCU",
    kind: "indian-universe",
    description: "Lokesh Kanagaraj's connected Tamil action universe: Kaithi, Vikram, and Leo.",
    aliases: ["lcu", "lokesh", "kaithi", "vikram", "leo", "kollywood universe"],
    orders: ["release"],
    movies: inOrder([
      ["Kaithi", "2019"],
      ["Vikram", "2022"],
      ["Leo", "2023"],
    ]),
  }),
  curated({
    id: "maddock-horror-comedy-universe",
    name: "Maddock Horror-Comedy Universe",
    shortName: "Horror-Comedy Universe",
    kind: "indian-universe",
    description: "Stree, Bhediya, Munjya, and Thamma — Maddock Films' connected Hindi horror-comedies.",
    aliases: ["stree", "bhediya", "munjya", "thamma", "maddock", "horror comedy universe"],
    orders: ["release"],
    movies: inOrder([
      ["Stree", "2018"],
      ["Bhediya", "2022"],
      ["Munjya", "2024"],
      ["Stree 2", "2024"],
      ["Thamma", "2025"],
    ]),
  }),
  curated({
    id: "harry-potter",
    name: "Harry Potter",
    shortName: "Harry Potter",
    kind: "scifi-fantasy",
    description: "Eight films, one continuous story — from Platform 9¾ to the Battle of Hogwarts.",
    aliases: ["harry potter", "hogwarts"],
    orders: ["release"],
    minimumMovies: 5,
    movies: inOrder([
      ["Harry Potter and the Philosopher's Stone", "2001"],
      ["Harry Potter and the Chamber of Secrets", "2002"],
      ["Harry Potter and the Prisoner of Azkaban", "2004"],
      ["Harry Potter and the Goblet of Fire", "2005"],
      ["Harry Potter and the Order of the Phoenix", "2007"],
      ["Harry Potter and the Half-Blood Prince", "2009"],
      ["Harry Potter and the Deathly Hallows: Part 1", "2010"],
      ["Harry Potter and the Deathly Hallows: Part 2", "2011"],
    ]),
  }),
  curated({
    id: "lord-of-the-rings",
    name: "The Lord of the Rings",
    shortName: "LOTR",
    kind: "scifi-fantasy",
    description: "The original trilogy — one continuous journey from the Shire to Mount Doom.",
    aliases: ["lord of the rings", "lotr"],
    orders: ["release"],
    movies: inOrder([
      ["The Lord of the Rings: The Fellowship of the Ring", "2001"],
      ["The Lord of the Rings: The Two Towers", "2002"],
      ["The Lord of the Rings: The Return of the King", "2003"],
    ]),
  }),
  curated({
    id: "mission-impossible",
    name: "Mission: Impossible",
    shortName: "Mission: Impossible",
    kind: "action",
    description: "Ethan Hunt's IMF missions, told in a single continuous line from 1996 to today.",
    aliases: ["mission impossible", "ethan hunt", "imf"],
    orders: ["release"],
    minimumMovies: 5,
    movies: inOrder([
      ["Mission: Impossible", "1996"],
      ["Mission: Impossible II", "2000"],
      ["Mission: Impossible III", "2006"],
      ["Mission: Impossible - Ghost Protocol", "2011"],
      ["Mission: Impossible - Rogue Nation", "2015"],
      ["Mission: Impossible - Fallout", "2018"],
      ["Mission: Impossible - Dead Reckoning Part One", "2023"],
      ["Mission: Impossible - The Final Reckoning", "2025"],
    ]),
  }),
];

// --- TMDB collection franchises (exact, verified collection names) ------------------------

const COLLECTIONS: JourneyDefinition[] = [
  // Action & adventure
  collection("james-bond", "James Bond", "action", ["James Bond"], "Every official 007 film, from Dr. No onward, in the order audiences met each Bond.", ["007", "bond"], "Bond"),
  collection("fast-and-furious", "Fast & Furious", "action", ["The Fast and the Furious"], "Street races to globe-trotting heists — the whole family saga in release order.", ["fast and furious", "furious", "dom toretto"]),
  collection("john-wick", "John Wick", "action", ["John Wick"], "The retired assassin's escalating war with the High Table.", ["baba yaga", "high table"]),
  collection("die-hard", "Die Hard", "action", ["Die Hard"], "John McClane, wrong place, wrong time — five times over.", ["john mcclane"]),
  collection("bourne", "Bourne", "action", ["The Bourne"], "The amnesiac agent's hunt for who he really is, plus the Legacy spin-off.", ["jason bourne", "bourne identity"]),
  collection("indiana-jones", "Indiana Jones", "action", ["Indiana Jones"], "The archaeologist-adventurer's five expeditions, from the Ark to the Dial.", ["indy", "raiders of the lost ark"]),
  collection("mad-max", "Mad Max", "action", ["Mad Max"], "The Wasteland saga, from the 1979 original to Fury Road and Furiosa.", ["fury road", "furiosa", "wasteland"]),
  collection("pirates-of-the-caribbean", "Pirates of the Caribbean", "action", ["Pirates of the Caribbean"], "Captain Jack Sparrow's voyages, in release order.", ["jack sparrow", "pirates"], "Pirates"),
  collection("transformers", "Transformers", "action", ["Transformers"], "Autobots, Decepticons, and the humans caught between them.", ["autobots", "optimus prime"]),
  collection("lethal-weapon", "Lethal Weapon", "action", ["Lethal Weapon"], "Riggs and Murtaugh, the buddy-cop series that defined the genre.", ["riggs", "murtaugh"]),
  collection("rambo", "Rambo", "action", ["Rambo"], "From First Blood to Last Blood — John Rambo's five films.", ["first blood", "john rambo"]),
  collection("the-karate-kid", "The Karate Kid", "action", ["The Karate Kid"], "Wax on, wax off — the original series, the 2010 remake, and Legends.", ["karate kid", "miyagi"]),
  collection("taken", "Taken", "action", ["Taken"], "Bryan Mills and his particular set of skills.", ["bryan mills"]),
  collection("the-expendables", "The Expendables", "action", ["The Expendables"], "An ensemble of action icons, four missions deep.", ["expendables"]),
  collection("bad-boys", "Bad Boys", "action", ["Bad Boys"], "Mike Lowrey and Marcus Burnett's Miami cases.", ["mike lowrey", "will smith"]),
  collection("rush-hour", "Rush Hour", "action", ["Rush Hour"], "Jackie Chan and Chris Tucker's action-comedy trilogy.", ["jackie chan", "chris tucker"]),
  collection("top-gun", "Top Gun", "action", ["Top Gun"], "Maverick, from the 1986 original to the 2022 sequel.", ["maverick"]),
  collection("the-mummy", "The Mummy", "action", ["The Mummy"], "Rick O'Connell's adventure trilogy, from Hamunaptra to the Dragon Emperor.", ["mummy"]),
  collection("national-treasure", "National Treasure", "action", ["National Treasure"], "Ben Gates' historical treasure hunts.", ["ben gates"]),
  collection("kingsman", "Kingsman", "action", ["Kingsman"], "The independent secret service, including The King's Man prequel.", ["kingsman"]),
  collection("jack-reacher", "Jack Reacher", "action", ["Jack Reacher"], "Lee Child's drifter-investigator on the big screen.", ["reacher"]),
  collection("the-equalizer", "The Equalizer", "action", ["The Equalizer"], "Robert McCall's quiet brand of justice, in three films.", ["robert mccall"]),
  collection("the-transporter", "The Transporter", "action", ["The Transporter"], "Frank Martin's rules-first courier jobs.", ["transporter", "jason statham"]),
  collection("beverly-hills-cop", "Beverly Hills Cop", "action", ["Beverly Hills Cop"], "Axel Foley's four Beverly Hills cases.", ["axel foley", "eddie murphy"]),
  collection("gladiator", "Gladiator", "action", ["Gladiator"], "The arena, from Maximus to Lucius.", ["maximus"]),
  collection("extraction", "Extraction", "action", ["Extraction"], "Tyler Rake's rescue missions.", ["tyler rake"]),

  // Superhero
  collection("the-avengers", "The Avengers", "superhero", ["The Avengers"], "The four team-up films at the heart of the MCU.", ["avengers"]),
  collection("iron-man", "Iron Man", "superhero", ["Iron Man"], "Tony Stark's solo trilogy.", ["tony stark"]),
  collection("captain-america", "Captain America", "superhero", ["Captain America"], "Steve Rogers' — and then Sam Wilson's — solo films.", ["steve rogers", "sam wilson"]),
  collection("thor", "Thor", "superhero", ["Thor"], "The God of Thunder's four solo films.", ["asgard"]),
  collection("guardians-of-the-galaxy", "Guardians of the Galaxy", "superhero", ["Guardians of the Galaxy"], "Star-Lord's found family, in three volumes.", ["star-lord", "groot", "guardians"]),
  collection("spider-man-raimi", "Spider-Man (Raimi Trilogy)", "superhero", ["Spider-Man"], "Sam Raimi's Tobey Maguire trilogy.", ["spider-man", "spiderman", "tobey maguire", "raimi"], "Spider-Man"),
  collection("the-amazing-spider-man", "The Amazing Spider-Man", "superhero", ["The Amazing Spider-Man"], "Andrew Garfield's two films.", ["andrew garfield", "amazing spider-man"]),
  collection("spider-man-mcu", "Spider-Man (MCU)", "superhero", ["Spider-Man (MCU)"], "Tom Holland's Spider-Man films inside the MCU.", ["tom holland", "homecoming", "no way home"]),
  collection("spider-verse", "Spider-Verse", "superhero", ["Spider-Man: Spider-Verse"], "Miles Morales and the animated multiverse of Spider-People.", ["miles morales", "spider-verse"]),
  collection("x-men", "X-Men", "superhero", ["X-Men"], "Fox's original X-Men series, in release order.", ["xmen", "mutants"]),
  collection("wolverine", "Wolverine", "superhero", ["The Wolverine"], "Hugh Jackman's solo Logan films, ending with Logan.", ["logan", "hugh jackman"]),
  collection("deadpool", "Deadpool", "superhero", ["Deadpool"], "The Merc with a Mouth, three films in.", ["wade wilson"]),
  collection("the-dark-knight", "The Dark Knight Trilogy", "superhero", ["The Dark Knight"], "Christopher Nolan's Batman trilogy.", ["dark knight", "nolan batman", "batman begins"], "Dark Knight"),
  collection("batman-1989", "Batman (1989–1997)", "superhero", ["Batman"], "The Burton and Schumacher Batman films.", ["batman", "michael keaton"], "Batman"),
  collection("superman-1978", "Superman (1978–1987)", "superhero", ["Superman"], "Christopher Reeve's four Superman films.", ["superman", "christopher reeve"], "Superman"),
  collection("wonder-woman", "Wonder Woman", "superhero", ["Wonder Woman"], "Diana Prince's two solo films.", ["diana prince"]),
  collection("aquaman", "Aquaman", "superhero", ["Aquaman"], "Arthur Curry's two solo films.", ["arthur curry"]),
  collection("shazam", "Shazam!", "superhero", ["Shazam"], "Billy Batson's two films.", ["shazam", "billy batson"]),
  collection("blade", "Blade", "superhero", ["Blade"], "Wesley Snipes' vampire-hunter trilogy.", ["daywalker"]),
  collection("hellboy", "Hellboy", "superhero", ["Hellboy"], "Guillermo del Toro's two Hellboy films.", ["del toro"]),
  collection("venom", "Venom", "superhero", ["Venom"], "Eddie Brock and the symbiote, three films.", ["eddie brock", "symbiote"]),

  // Sci-fi & fantasy
  collection("the-matrix", "The Matrix", "scifi-fantasy", ["The Matrix"], "Take the red pill — Neo's story in release order.", ["matrix", "neo"], "Matrix"),
  collection("terminator", "The Terminator", "scifi-fantasy", ["The Terminator"], "Judgment Day and the machines sent back to stop it.", ["terminator", "skynet"], "Terminator"),
  collection("alien", "Alien", "scifi-fantasy", ["Alien"], "In space, no one can hear you scream — the Alien films in release order.", ["xenomorph", "ripley"]),
  collection("predator", "Predator", "scifi-fantasy", ["Predator"], "The hunt, from the jungle to the city and beyond.", ["yautja"]),
  collection("alien-vs-predator", "Alien vs. Predator", "scifi-fantasy", ["AVP"], "The two crossover films.", ["avp", "alien vs predator"], "AVP"),
  collection("planet-of-the-apes", "Planet of the Apes", "scifi-fantasy", ["Planet of the Apes (Original)", "Planet of the Apes (Reboot)"], "The original series and the modern reboot saga, in release order.", ["apes", "caesar"], "Apes"),
  collection("jurassic-park", "Jurassic Park & Jurassic World", "scifi-fantasy", ["Jurassic Park"], "Life finds a way — from Isla Nublar to dinosaurs loose in the world.", ["jurassic", "dinosaurs", "jurassic world"], "Jurassic"),
  collection("star-trek-original", "Star Trek: The Original Series Films", "scifi-fantasy", ["Star Trek: The Original Series"], "Kirk and Spock's six films with the original crew.", ["star trek", "kirk", "spock", "wrath of khan"], "Star Trek (TOS)"),
  collection("star-trek-next-generation", "Star Trek: The Next Generation Films", "scifi-fantasy", ["Star Trek: The Next Generation"], "Picard's crew in four films.", ["picard", "next generation"], "Star Trek (TNG)"),
  collection("star-trek-kelvin", "Star Trek (Kelvin Timeline)", "scifi-fantasy", ["Star Trek: Alternate Reality"], "The 2009 reboot trilogy.", ["star trek 2009", "kelvin"], "Star Trek (2009)"),
  collection("back-to-the-future", "Back to the Future", "scifi-fantasy", ["Back to the Future"], "Marty and Doc's trilogy through time.", ["marty mcfly", "doc brown", "delorean"]),
  collection("men-in-black", "Men in Black", "scifi-fantasy", ["Men in Black"], "Agents J and K keep Earth's alien residents in line.", ["mib", "agent j"]),
  collection("avatar", "Avatar", "scifi-fantasy", ["Avatar"], "James Cameron's Pandora saga.", ["pandora", "navi", "james cameron"]),
  collection("dune", "Dune", "scifi-fantasy", ["Dune"], "Denis Villeneuve's adaptation of Frank Herbert's novel.", ["arrakis", "paul atreides"]),
  collection("hunger-games", "The Hunger Games", "scifi-fantasy", ["The Hunger Games"], "Panem's rebellion, film by film.", ["hunger games", "katniss", "panem"], "Hunger Games"),
  collection("the-maze-runner", "The Maze Runner", "scifi-fantasy", ["The Maze Runner"], "Thomas and the Gladers, three films.", ["maze runner"]),
  collection("divergent", "Divergent", "scifi-fantasy", ["Divergent"], "Tris Prior and the factions, three films.", ["tris", "insurgent", "allegiant"]),
  collection("twilight", "The Twilight Saga", "scifi-fantasy", ["Twilight"], "Bella, Edward, and Jacob — all five films.", ["twilight", "bella", "edward cullen"], "Twilight"),
  collection("the-chronicles-of-narnia", "The Chronicles of Narnia", "scifi-fantasy", ["The Chronicles of Narnia"], "Through the wardrobe — three Narnia films.", ["narnia", "aslan"], "Narnia"),
  collection("percy-jackson", "Percy Jackson", "scifi-fantasy", ["Percy Jackson"], "The demigod's two films.", ["percy jackson", "olympians"]),
  collection("pacific-rim", "Pacific Rim", "scifi-fantasy", ["Pacific Rim"], "Jaegers versus Kaiju.", ["jaegers", "kaiju"]),
  collection("riddick", "Riddick", "scifi-fantasy", ["The Chronicles of Riddick"], "Pitch Black and its sequels.", ["pitch black", "vin diesel"]),
  collection("tron", "TRON", "scifi-fantasy", ["Tron"], "Inside the Grid, from 1982 to Ares.", ["tron"]),

  // Animated
  collection("toy-story", "Toy Story", "animated", ["Toy Story"], "Woody, Buzz, and the whole toy box, in release order.", ["woody", "buzz lightyear", "pixar"]),
  collection("shrek", "Shrek", "animated", ["Shrek"], "The ogre, the donkey, and far, far away.", ["far far away"]),
  collection("kung-fu-panda", "Kung Fu Panda", "animated", ["Kung Fu Panda"], "Po's path to Dragon Warrior and beyond.", ["po", "dragon warrior"]),
  collection("despicable-me", "Despicable Me", "animated", ["Despicable Me"], "Gru, the girls, and a lot of Minions.", ["gru"]),
  collection("minions", "Minions", "animated", ["Minions"], "The Minions' own films.", ["minions"]),
  collection("ice-age", "Ice Age", "animated", ["Ice Age"], "Manny, Sid, Diego, and Scrat's squirrel-sized chaos.", ["scrat", "sid"]),
  collection("how-to-train-your-dragon", "How to Train Your Dragon", "animated", ["How to Train Your Dragon"], "Hiccup and Toothless, a trilogy.", ["toothless", "hiccup"]),
  collection("madagascar", "Madagascar", "animated", ["Madagascar"], "Alex, Marty, Melman, and Gloria's escapes.", ["penguins"]),
  collection("cars", "Cars", "animated", ["Cars"], "Lightning McQueen's three races.", ["lightning mcqueen"]),
  collection("frozen", "Frozen", "animated", ["Frozen"], "Anna and Elsa, two films.", ["elsa", "anna"]),
  collection("the-incredibles", "The Incredibles", "animated", ["The Incredibles"], "The Parr family's superhero adventures.", ["incredibles"]),
  collection("finding-nemo", "Finding Nemo", "animated", ["Finding Nemo"], "Nemo, then Dory.", ["dory"]),
  collection("monsters-inc", "Monsters, Inc.", "animated", ["Monsters, Inc."], "Mike and Sulley, at work and at university.", ["sulley", "mike wazowski"]),
  collection("inside-out", "Inside Out", "animated", ["Inside Out"], "Riley's emotions, two films.", ["joy", "riley"]),
  collection("zootopia", "Zootopia", "animated", ["Zootopia"], "Judy Hopps and Nick Wilde's cases.", ["zootopia", "judy hopps"]),
  collection("moana", "Moana", "animated", ["Moana"], "Moana's voyages.", ["maui"]),
  collection("hotel-transylvania", "Hotel Transylvania", "animated", ["Hotel Transylvania"], "Drac's monster hotel, four films.", ["dracula"]),
  collection("the-lion-king", "The Lion King (Animated)", "animated", ["The Lion King"], "The 1994 classic and its animated follow-ups.", ["simba", "lion king"], "Lion King"),
  collection("wreck-it-ralph", "Wreck-It Ralph", "animated", ["Wreck-It Ralph"], "Ralph and Vanellope, arcade to internet.", ["vanellope"]),
  collection("sing", "Sing", "animated", ["Sing"], "Buster Moon's singing competitions.", ["buster moon"]),
  collection("the-secret-life-of-pets", "The Secret Life of Pets", "animated", ["The Secret Life of Pets"], "What pets do when their owners leave.", ["secret life of pets"]),
  collection("rio", "Rio", "animated", ["Rio"], "Blu the macaw, two films.", ["blu"]),
  collection("cloudy-with-a-chance-of-meatballs", "Cloudy with a Chance of Meatballs", "animated", ["Cloudy with a Chance of Meatballs"], "Flint Lockwood's food-weather inventions.", ["flint lockwood"]),
  collection("puss-in-boots", "Puss in Boots", "animated", ["Puss in Boots"], "Shrek's swashbuckling cat, solo.", ["puss in boots"]),

  // Family
  collection("home-alone", "Home Alone", "family", ["Home Alone"], "Holiday booby traps, from Kevin McCallister onward.", ["kevin mccallister"]),
  collection("paddington", "Paddington", "family", ["Paddington"], "The marmalade-loving bear's three films.", ["paddington bear"]),
  collection("jumanji", "Jumanji", "family", ["Jumanji"], "The game that pulls players in — 1995 original and the Jungle sequels.", ["jumanji"]),
  collection("night-at-the-museum", "Night at the Museum", "family", ["Night at the Museum"], "Larry Daley's exhibits come alive, three films.", ["larry daley"]),
  collection("sonic-the-hedgehog", "Sonic the Hedgehog", "family", ["Sonic the Hedgehog"], "Sonic's live-action films.", ["sonic", "knuckles"]),
  collection("stuart-little", "Stuart Little", "family", ["Stuart Little"], "The Little family's mouse.", ["stuart little"]),
  collection("the-santa-clause", "The Santa Clause", "family", ["The Santa Clause"], "Scott Calvin's Santa trilogy.", ["santa clause"]),
  collection("alvin-and-the-chipmunks", "Alvin and the Chipmunks", "family", ["Alvin and the Chipmunks"], "Alvin, Simon, and Theodore's four films.", ["chipmunks"]),
  collection("wicked", "Wicked", "family", ["Wicked"], "The musical's two-part adaptation.", ["elphaba", "glinda"]),
  collection("enola-holmes", "Enola Holmes", "family", ["Enola Holmes"], "Sherlock's younger sister's own cases.", ["enola"]),

  // Comedy
  collection("the-hangover", "The Hangover", "comedy", ["The Hangover"], "The Wolfpack's three disastrous trips.", ["wolfpack"]),
  collection("meet-the-parents", "Meet the Parents", "comedy", ["Meet the Parents"], "Greg Focker versus his father-in-law.", ["fockers"]),
  collection("american-pie", "American Pie", "comedy", ["American Pie"], "The theatrical American Pie films.", ["american pie"]),
  collection("pitch-perfect", "Pitch Perfect", "comedy", ["Pitch Perfect"], "The Barden Bellas, three films.", ["bellas"]),
  collection("jump-street", "21 & 22 Jump Street", "comedy", ["Jump Street"], "Schmidt and Jenko go undercover.", ["21 jump street", "22 jump street"], "Jump Street"),
  collection("austin-powers", "Austin Powers", "comedy", ["Austin Powers"], "The International Man of Mystery, yeah baby.", ["dr evil"]),
  collection("ace-ventura", "Ace Ventura", "comedy", ["Ace Ventura"], "Jim Carrey's pet detective.", ["pet detective", "jim carrey"]),
  collection("anchorman", "Anchorman", "comedy", ["Anchorman"], "Ron Burgundy, two films.", ["ron burgundy"]),
  collection("bill-and-ted", "Bill & Ted", "comedy", ["Bill & Ted"], "Most excellent time travel, three films.", ["bill and ted"]),
  collection("zombieland", "Zombieland", "comedy", ["Zombieland"], "The rules of surviving the zombie apocalypse.", ["zombieland"]),
  collection("ghostbusters", "Ghostbusters", "comedy", ["Ghostbusters"], "Who you gonna call — the original films and the Afterlife sequels.", ["ghostbusters"]),
  collection("gremlins", "Gremlins", "comedy", ["Gremlins"], "Never feed them after midnight.", ["gizmo"]),
  collection("police-academy", "Police Academy", "comedy", ["Police Academy"], "The academy's seven films.", ["police academy"]),
  collection("scary-movie", "Scary Movie", "comedy", ["Scary Movie"], "The horror-parody series.", ["scary movie"]),
  collection("ted", "Ted", "comedy", ["Ted"], "John and his foul-mouthed teddy bear.", ["ted"]),
  collection("the-addams-family", "The Addams Family", "comedy", ["The Addams Family"], "The 1990s live-action Addams Family films.", ["addams family", "wednesday"]),
  collection("legally-blonde", "Legally Blonde", "comedy", ["Legally Blonde"], "Elle Woods takes on law school and Washington.", ["elle woods"]),

  // Horror
  collection("halloween", "Halloween", "horror", ["Halloween"], "Michael Myers and Laurie Strode, across every Halloween film.", ["michael myers"]),
  collection("scream", "Scream", "horror", ["Scream"], "Ghostface and the rules of the slasher.", ["ghostface"]),
  collection("saw", "Saw", "horror", ["Saw"], "Jigsaw's games, all ten films.", ["jigsaw"]),
  collection("insidious", "Insidious", "horror", ["Insidious"], "The Further and the Lambert family.", ["the further"]),
  collection("final-destination", "Final Destination", "horror", ["Final Destination"], "You can't cheat death — six films.", ["final destination"]),
  collection("a-nightmare-on-elm-street", "A Nightmare on Elm Street", "horror", ["A Nightmare on Elm Street"], "Freddy Krueger's original run.", ["freddy krueger"]),
  collection("friday-the-13th", "Friday the 13th", "horror", ["Friday the 13th"], "Jason Voorhees and Camp Crystal Lake.", ["jason voorhees"]),
  collection("childs-play", "Child's Play", "horror", ["Child's Play"], "Chucky's original series.", ["chucky"]),
  collection("the-exorcist", "The Exorcist", "horror", ["The Exorcist"], "The original and every Exorcist follow-up.", ["exorcist"]),
  collection("evil-dead", "Evil Dead", "horror", ["Evil Dead"], "Sam Raimi's original trilogy with Ash.", ["ash williams", "necronomicon"]),
  collection("the-purge", "The Purge", "horror", ["The Purge"], "One night a year, all crime is legal.", ["purge"]),
  collection("paranormal-activity", "Paranormal Activity", "horror", ["Paranormal Activity"], "The found-footage haunting series.", ["found footage"]),
  collection("a-quiet-place", "A Quiet Place", "horror", ["A Quiet Place"], "Survive by staying silent.", ["quiet place"]),
  collection("it", "It", "horror", ["It"], "Pennywise and the Losers' Club, two chapters.", ["pennywise"]),
  collection("the-ring", "The Ring", "horror", ["The Ring"], "The cursed videotape films.", ["samara"]),
  collection("the-grudge", "The Grudge", "horror", ["The Grudge"], "The American Grudge trilogy.", ["the grudge"]),
  collection("resident-evil", "Resident Evil", "horror", ["Resident Evil"], "Alice versus the Umbrella Corporation, six films.", ["umbrella corporation"]),
  collection("underworld", "Underworld", "horror", ["Underworld"], "Vampires versus Lycans, five films.", ["selene", "lycans"]),
  collection("28-days-later", "28 Days / Weeks / Years Later", "horror", ["28 Days/Weeks/Years Later"], "The rage-virus saga.", ["28 days later", "28 years later"], "28 Days Later"),
  collection("jaws", "Jaws", "horror", ["Jaws"], "The shark, four films.", ["amity island"]),
  collection("terrifier", "Terrifier", "horror", ["Terrifier"], "Art the Clown's slasher series.", ["art the clown"]),
  collection("smile", "Smile", "horror", ["Smile"], "The smiling curse, two films.", ["smile"]),
  collection("sinister", "Sinister", "horror", ["Sinister"], "Bughuul's found films.", ["bughuul"]),

  // Crime & thriller
  collection("the-godfather", "The Godfather", "crime-thriller", ["The Godfather"], "The Corleone family trilogy.", ["corleone", "godfather"]),
  collection("oceans", "Ocean's Trilogy", "crime-thriller", ["Ocean's"], "Danny Ocean's crew and their heists.", ["oceans eleven", "danny ocean"], "Ocean's"),
  collection("now-you-see-me", "Now You See Me", "crime-thriller", ["Now You See Me"], "The Four Horsemen's magic heists.", ["four horsemen"]),
  collection("knives-out", "Knives Out", "crime-thriller", ["Knives Out"], "Benoit Blanc's mysteries.", ["benoit blanc", "glass onion"]),
  collection("sherlock-holmes", "Sherlock Holmes (Ritchie)", "crime-thriller", ["Sherlock Holmes"], "Guy Ritchie's two Sherlock Holmes films.", ["sherlock"], "Sherlock Holmes"),
  collection("sicario", "Sicario", "crime-thriller", ["Sicario"], "The cartel-war thrillers.", ["sicario"]),
  collection("dirty-harry", "Dirty Harry", "crime-thriller", ["Dirty Harry"], "Clint Eastwood's Inspector Harry Callahan.", ["harry callahan", "clint eastwood"]),
  collection("kill-bill", "Kill Bill", "crime-thriller", ["Kill Bill"], "The Bride's revenge, in two volumes.", ["the bride", "tarantino"]),

  // Drama & romance
  collection("rocky-creed", "Rocky & Creed", "drama-romance", ["Rocky", "Creed"], "From Philadelphia underdog to mentor — the Rocky films and their Creed continuation.", ["rocky balboa", "adonis creed", "boxing"], "Rocky"),
  collection("before-trilogy", "The Before Trilogy", "drama-romance", ["Before..."], "Jesse and Céline, nine years apart each time.", ["before sunrise", "before sunset", "before midnight"], "Before Trilogy"),
  collection("to-all-the-boys", "To All the Boys", "drama-romance", ["To All the Boys"], "Lara Jean's love letters, three films.", ["lara jean"]),

  // Indian
  collection("baahubali", "Bāhubali", "indian", ["Bāhubali"], "S. S. Rajamouli's two-part Telugu epic.", ["baahubali", "bahubali", "rajamouli", "prabhas"]),
  collection("kgf", "K.G.F", "indian", ["K.G.F"], "Rocky's rise in the Kolar Gold Fields — the two-chapter Kannada saga.", ["kgf", "k.g.f", "yash", "rocky bhai"]),
  collection("pushpa", "Pushpa", "indian", ["Pushpa"], "Allu Arjun's red-sandalwood smuggler saga.", ["pushpa", "allu arjun"]),
  collection("kantara", "Kantara", "indian", ["Kantara"], "Rishab Shetty's Kannada folklore films.", ["kantara", "rishab shetty"]),
  collection("hit-verse", "HIT Verse", "indian", ["HIT Verse"], "The Homicide Intervention Team cases, in Telugu.", ["hit", "homicide intervention team", "hit the first case"]),
  collection("karthikeya", "Karthikeya", "indian", ["Karthikeya"], "Nikhil Siddhartha's mystery-adventure films.", ["karthikeya"]),
  collection("fun-and-frustration", "F2 / F3: Fun and Frustration", "indian", ["Fun and Frustration"], "Venkatesh and Varun Tej's Telugu family comedies.", ["f2", "f3"], "F2 & F3"),
  collection("singam", "Singam (Tamil)", "indian", ["Singam"], "Suriya's Tamil cop trilogy.", ["singam", "suriya"], "Singam"),
  collection("enthiran", "Enthiran", "indian", ["Enthiran"], "Shankar and Rajinikanth's robot films, Enthiran and 2.0.", ["robot", "2.0", "chitti", "rajinikanth"]),
  collection("kanchana", "Kanchana", "indian", ["Kanchana"], "Raghava Lawrence's Tamil horror-comedies.", ["kanchana", "muni", "raghava lawrence"]),
  collection("vishwaroopam", "Vishwaroopam", "indian", ["Vishwaroopam"], "Kamal Haasan's two-part spy thriller.", ["vishwaroopam", "kamal haasan"]),
  collection("aranmanai", "Aranmanai", "indian", ["Aranmanai"], "Sundar C's Tamil horror-comedies.", ["aranmanai"]),
  collection("maari", "Maari", "indian", ["Maari"], "Dhanush's Maari films.", ["maari", "dhanush"]),
  collection("jigarthanda", "Jigarthanda", "indian", ["Jigarthanda Series"], "Karthik Subbaraj's Jigarthanda films.", ["jigarthanda", "karthik subbaraj"]),
  collection("lucifer", "Lucifer", "indian", ["Lucifer"], "Prithviraj and Mohanlal's Malayalam political thrillers, Lucifer and L2: Empuraan.", ["lucifer", "empuraan", "mohanlal"]),
  collection("aadu", "Aadu", "indian", ["Aadu"], "Shaji Pappan's Malayalam cult comedies.", ["aadu", "shaji pappan"]),
  collection("cbi-series", "CBI (Sethurama Iyer)", "indian", ["CBI film series"], "Mammootty's Sethurama Iyer investigations.", ["cbi", "sethurama iyer", "mammootty"], "CBI"),
  collection("drishyam-hindi", "Drishyam (Hindi)", "indian", ["Drishyam"], "Ajay Devgn's Hindi Drishyam films.", ["drishyam", "ajay devgn"], "Drishyam"),
  collection("dhoom", "Dhoom", "indian", ["Dhoom"], "Yash Raj's heist-chase trilogy.", ["dhoom"]),
  collection("krrish", "Krrish", "indian", ["Krrish"], "Koi... Mil Gaya and Hrithik Roshan's superhero sequels.", ["krrish", "koi mil gaya", "hrithik roshan"]),
  collection("golmaal", "Golmaal", "indian", ["Golmaal"], "Rohit Shetty's comedy series, four films.", ["golmaal"]),
  collection("housefull", "Housefull", "indian", ["Housefull"], "The ensemble comedy series, five films.", ["housefull", "akshay kumar"]),
  collection("munna-bhai", "Munna Bhai", "indian", ["Munna Bhai"], "Munna and Circuit, two films.", ["munna bhai", "circuit", "sanjay dutt"]),
  collection("hera-pheri", "Hera Pheri", "indian", ["Hera Pheri"], "Raju, Shyam, and Baburao.", ["hera pheri", "baburao"]),
  collection("dabangg", "Dabangg", "indian", ["Dabangg"], "Chulbul Pandey's three films.", ["dabangg", "chulbul pandey"]),
  collection("race", "Race", "indian", ["Race"], "The Race thriller series.", ["race"]),
  collection("don", "Don", "indian", ["Don"], "Shah Rukh Khan's Don films.", ["don"]),
  collection("jolly-llb", "Jolly LLB", "indian", ["Jolly LLB"], "The courtroom comedy-dramas.", ["jolly llb"]),
  collection("bhool-bhulaiyaa", "Bhool Bhulaiyaa", "indian", ["Bhool Bhulaiyaa"], "The horror-comedy series, three films.", ["bhool bhulaiyaa", "manjulika"]),
  collection("gadar", "Gadar", "indian", ["Gadar"], "Tara Singh's two films.", ["gadar", "sunny deol"]),
  collection("welcome", "Welcome", "indian", ["Welcome"], "Majnu and Uday's comedy series.", ["welcome", "majnu bhai"]),
  collection("dhamaal", "Dhamaal", "indian", ["Dhamaal"], "The treasure-hunt comedies.", ["dhamaal"]),
  collection("fukrey", "Fukrey", "indian", ["Fukrey"], "The Fukrey boys' schemes.", ["fukrey"]),
  collection("tanu-weds-manu", "Tanu Weds Manu", "indian", ["Tanu Weds Manu"], "Aanand L. Rai's romantic comedies.", ["tanu weds manu", "kangana"]),
  collection("baaghi", "Baaghi", "indian", ["Baaghi"], "Tiger Shroff's action series.", ["baaghi", "tiger shroff"]),
  collection("abcd", "ABCD", "indian", ["ABCD"], "The dance-film series.", ["abcd", "any body can dance"]),
  collection("commando", "Commando", "indian", ["Commando"], "Vidyut Jammwal's action series.", ["commando", "vidyut jammwal"]),
  collection("raaz", "Raaz", "indian", ["Raaz"], "The Bhatt horror series.", ["raaz"]),
  collection("1920", "1920", "indian", ["1920"], "Vikram Bhatt's period horror series.", ["1920 horror"]),
  collection("murder", "Murder", "indian", ["Murder"], "The Bhatt thriller series.", ["murder"]),
  collection("aashiqui", "Aashiqui", "indian", ["Aashiqui"], "The musical romances, 1990 and 2013.", ["aashiqui"]),
  collection("heropanti", "Heropanti", "indian", ["Heropanti"], "Tiger Shroff's Heropanti films.", ["heropanti"]),

  // World cinema
  collection("ip-man", "Ip Man", "world", ["Ip Man"], "Donnie Yen as the Wing Chun grandmaster.", ["wing chun", "donnie yen"]),
  collection("police-story", "Police Story", "world", ["Police Story"], "Jackie Chan's Hong Kong cop series.", ["jackie chan", "police story"]),
  collection("infernal-affairs", "Infernal Affairs", "world", ["Infernal Affairs"], "The Hong Kong undercover trilogy.", ["infernal affairs"]),
  collection("once-upon-a-time-in-china", "Once Upon a Time in China", "world", ["Once Upon a Time in China"], "Wong Fei-hung's martial-arts saga.", ["wong fei-hung", "jet li"]),
  collection("detective-chinatown", "Detective Chinatown", "world", ["Detective Chinatown"], "The Chinese comedy-mystery series.", ["detective chinatown"]),
  collection("the-wandering-earth", "The Wandering Earth", "world", ["The Wandering Earth"], "China's sci-fi epics.", ["wandering earth"]),
  collection("wolf-warrior", "Wolf Warrior", "world", ["Wolf Warrior"], "The Chinese action series.", ["wolf warrior"]),
  collection("train-to-busan", "Train to Busan", "world", ["Train to Busan"], "Korea's zombie-outbreak films, Train to Busan and Peninsula.", ["peninsula", "korean zombie"]),
  collection("along-with-the-gods", "Along with the Gods", "world", ["Along with the Gods"], "Korea's afterlife fantasy two-parter.", ["along with the gods"]),
  collection("rurouni-kenshin", "Rurouni Kenshin", "world", ["Rurouni Kenshin"], "The live-action Japanese samurai saga.", ["kenshin", "samurai x"]),
  collection("rebuild-of-evangelion", "Rebuild of Evangelion", "world", ["Rebuild of Evangelion"], "The four Evangelion films.", ["evangelion", "eva"]),
  collection("the-raid", "The Raid", "world", ["The Raid"], "Indonesia's martial-arts action films.", ["the raid", "silat"]),
  collection("three-colors", "Three Colours", "world", ["Three Colors"], "Krzysztof Kieślowski's Blue, White, Red.", ["three colors", "three colours", "kieslowski"]),
  collection("millennium", "Millennium (Swedish)", "world", ["Millennium"], "The Swedish Dragon Tattoo trilogy.", ["dragon tattoo", "lisbeth salander"], "Millennium"),
  collection("taxi", "Taxi", "world", ["Taxi"], "The French action-comedy series.", ["taxi"]),
  collection("oss-117", "OSS 117", "world", ["OSS 117"], "The French spy-parody films.", ["oss 117"]),
  collection("district-13", "District 13", "world", ["District 13"], "The French parkour action films.", ["district b13", "banlieue 13"]),
  collection("pusher", "Pusher", "world", ["Pusher"], "Nicolas Winding Refn's Copenhagen crime trilogy.", ["pusher", "refn"]),
];

export const FRANCHISE_JOURNEYS: JourneyDefinition[] = [...CURATED, ...COLLECTIONS];
